import 'package:hive/hive.dart';

part 'transaction.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0)
enum TransactionType {
  @HiveField(0)
  income,
  
  @HiveField(1)
  expense
}

@HiveType(typeId: 1)
class Transaction extends HiveObject {
  @HiveField(0)
  final String id;
  
  @HiveField(1)
  final String title;
  
  @HiveField(2)
  final double amount;
  
  @HiveField(3)
  final DateTime date;
  
  @HiveField(4)
  final TransactionType type;
  
  @HiveField(5)
  final String category;
  
  @HiveField(6)
  final String? note;

  Transaction({
    required this.id,
    required this.title,
    required this.amount,
    required this.date,
    required this.type,
    required this.category,
    this.note,
  });
}

// IMPORTANT: Run the following command to generate the adapter files:
// flutter pub run build_runner build

