// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZagYAMdwQncqoFYMdZ5GyS6gcECcNNNs',
    appId: '1:990660848863:web:83b9883c4767a7bd79cd6a',
    messagingSenderId: '990660848863',
    projectId: 'financetracker-8cb19',
    authDomain: 'financetracker-8cb19.firebaseapp.com',
    storageBucket: 'financetracker-8cb19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA17ktC55VgHZSaQmLjzwTJsbpLyo71oRA',
    appId: '1:990660848863:android:dad94ca693dd594779cd6a',
    messagingSenderId: '990660848863',
    projectId: 'financetracker-8cb19',
    storageBucket: 'financetracker-8cb19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0QXLE_JJnKSNHSfoNNJKa2C90H-eTwkE',
    appId: '1:990660848863:ios:c7b65eeabea7e10179cd6a',
    messagingSenderId: '990660848863',
    projectId: 'financetracker-8cb19',
    storageBucket: 'financetracker-8cb19.firebasestorage.app',
    iosBundleId: 'com.example.financetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0QXLE_JJnKSNHSfoNNJKa2C90H-eTwkE',
    appId: '1:990660848863:ios:c7b65eeabea7e10179cd6a',
    messagingSenderId: '990660848863',
    projectId: 'financetracker-8cb19',
    storageBucket: 'financetracker-8cb19.firebasestorage.app',
    iosBundleId: 'com.example.financetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZagYAMdwQncqoFYMdZ5GyS6gcECcNNNs',
    appId: '1:990660848863:web:321089f8cd65774579cd6a',
    messagingSenderId: '990660848863',
    projectId: 'financetracker-8cb19',
    authDomain: 'financetracker-8cb19.firebaseapp.com',
    storageBucket: 'financetracker-8cb19.firebasestorage.app',
  );
}
